#!/bin/bash 
 
mv Relief.cc ../src 
mv Relief.hh ../include 
 
mv Parameters.joblib ../RowData 
 
mv Events.joblib ../Executables 
 
mv DCR_10m_0rad_25cm.cc ../src 
cd ../src 
mv DCR_10m_0rad_25cm.cc DetectorConstruction.cc 
cd ../ 
rm -r build 
mkdir build 
cd build 
rm -rf * 
cmake ../ 
make 
mv Muons MuonsR_10m_0rad_25cm 
mv MuonsR_10m_0rad_25cm ../Executables/ 
cd ../src 
mv DetectorConstruction.cc DCR_10m_0rad_25cm.cc 
mv DCR_10m_0rad_25cm.cc ../Source 
 
cd ../Source 
mv DCS_10m_0rad_25cm.cc ../src 
cd ../src 
mv DCS_10m_0rad_25cm.cc DetectorConstruction.cc 
cd ../ 
rm -r build 
mkdir build 
cd build 
rm -rf * 
cmake ../ 
make 
mv Muons MuonsS_10m_0rad_25cm 
mv MuonsS_10m_0rad_25cm ../Executables/ 
cd ../src 
mv DetectorConstruction.cc DCS_10m_0rad_25cm.cc 
mv DCS_10m_0rad_25cm.cc ../Source 
 
cd ../Source 
bash Run